### ISSUE TITLE
Externalize hardcoded strings into the strings.xml file

### ISSUE THREAD

**Issue by ahmed-nabil-elagder** [OmarShafei-coder/Hatholy#1]
Try to externalize hardcoded strings like the below one into the `strings.xml` file

https://github.com/OmarShafei-coder/Hatholy/blob/e59c0f7b894e28036928de6ea7a790ae622b09d7/app/src/main/java/com/omarshafei/hatholy/ui/AddPost/AddPostFragment.java#L147

**Comment by OmarShafei-coder** [comment]
Thanks for your time, Really appreciate it.
I will use Arabic only in the app, but if you know other purposes to do
that please let me know.

**Comment by ahmed-nabil-elagder** [comment]
Greate Omar, I will list to you why **externalize hardcoded strings** (_whatever the language you will use_) is a good practice however if your application will support one language (Arabic in our case).  

- In case of one string is used in multiple locations, the current behavior, you will take a cycle to update all, but if your externalize it, you will update it once in one place.
- It will help you to apply (Separation of concerns) principle, which keeps your later modification safe (not update the main classes when you will just need to update strings values).

Good luck Omar!

**Comment by OmarShafei-coder** [comment]
Thanks so much for your time. I get it.

**Comment by OmarShafei-coder** [comment]
Done bro with help of @hamza94max
